### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by deathiop** [dgrandemange/tinyCbCom4jPos#1]
Is that code open? :)

**Comment by dgrandemange** [comment]
Some classes extends some JPos framework classes (mainly org.jpos.iso.BaseChannel among others) which itself is licensed under GNU AFFERO GENERAL PUBLIC LICENSE
So i suppose this code should also be licensed under AGPL.

**Comment by deathiop** [comment]
Do you think it would be possible to split the cb2a implementation and the JPos bind parts?
In a word, the code you have here is really interesting, but the contamination of the AGPL license forbids anyone to build something one might want to use in a professional use (without buying JPos here). I'm not interesseted in JPos, hence my question. 
In other words: would you agree to put the JPos-less cb2a part under the GPL license?

Thanks for you time anyway :).

**Comment by dgrandemange** [comment]
I've just created a new dedicated GitHub repository https://github.com/dgrandemange/cbcom which will only contain the cbcom related parts (which means excluding the iso package actually). I'll also consider make this repo a maven project. Will try to make it available in a few days.

**Comment by dgrandemange** [comment]
CBCOM classes are now available under GPL v2 license and are also released under maven central repository.
